# Generated by Django 3.2.15 on 2022-09-13 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='paused',
        ),
        migrations.AddField(
            model_name='datasource',
            name='quoted_newlines',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='frequency_delta_minutes',
            field=models.DurationField(
                default=datetime.timedelta(seconds=1800),
                help_text='How long to wait for the next execution, defaults to 30 minutes'),
        ),
        migrations.AddField(
            model_name='transformation',
            name='order',
            field=models.IntegerField(blank=True,
                                      default=None,
                                      help_text='Order in which it will be executed in the pipeline',
                                      null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='connection_string',
            field=models.CharField(blank=True,
                                   default=None,
                                   help_text='Ignored if Google BigQuery. File path if CSV.',
                                   max_length=250,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='database',
            field=models.CharField(blank=True,
                                   default=None,
                                   help_text='Ignored if Heroku or CSV.',
                                   max_length=250,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecution',
            name='log',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pipelineexecution',
            name='status',
            field=models.CharField(choices=[('LOADING', 'Loading'), ('OPERATIONAL', 'Operational'),
                                            ('MINOR', 'Minor'), ('CRITICAL', 'Critical')],
                                   default='LOADING',
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='pipelineexecution',
            name='stdout',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='stdout',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
