# Generated by Django 3.2.15 on 2022-10-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0002_auto_20220913_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='slug',
            field=models.SlugField(default=None, null=True),
        ),
        migrations.RemoveField(
            model_name='pipeline',
            name='source_from',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_from',
            field=models.ManyToManyField(blank=True,
                                         related_name='pipeline_from_set',
                                         to='dataflow.DataSource'),
        ),
    ]
