# Generated by Django 3.2.16 on 2022-11-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0004_alter_datasource_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='table_name',
            field=models.TextField(blank=True, default=None, help_text='Ignored for CSV. You can write a SELECT query statement, but for Heroku, SQL or Big Query only.', null=True),
        ),
    ]
