# Generated by Django 3.2.16 on 2023-01-19 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0006_pipelineexecution_incoming_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_pull',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pipelineexecution',
            name='incoming_stream',
            field=models.JSONField(blank=True, default=None, help_text='If set, the pipeline will be treated like a stream', null=True),
        ),
    ]
