# Generated by Django 3.2.16 on 2023-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0007_auto_20230119_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_pull',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
