# Generated by Django 3.2.16 on 2023-01-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataflow', '0007_alter_pipelineexecution_incoming_stream'),
        ('dataflow', '0008_alter_project_last_pull'),
    ]

    operations = [
    ]
